Repository Automattic/abacus, pull requests merged in 2020-07, with the labels that each got.

#182 Update ExperimentTabs to Use MUI Tabs
  components/ExperimentTabs.test.tsx
  components/ExperimentTabs.tsx
  pages/experiments/[id].tsx
  pages/experiments/[id]/results.tsx
  styles/theme.ts
Labels: [!priority] high, [component] experimenter interface, [type] enhancement

#187 Add and Use Label Component
  components/Label.tsx
  components/MetricAssignmentsPanel.test.tsx
  components/MetricAssignmentsPanel.tsx
  components/SegmentsTable.test.tsx
  components/SegmentsTable.tsx
  components/VariationsTable.tsx
  components/__snapshots__/AudiencePanel.test.tsx.snap
  components/__snapshots__/ExperimentDetails.test.tsx.snap
Labels: [!priority] high, [component] experimenter interface, [type] enhancement

#184 Adjust Heading Size and Spacing
  components/Headings.stories.tsx
  components/LabelValuePanel.tsx
  components/Layout.tsx
  styles/theme.ts
Labels: [!priority] high, [component] experimenter interface, [type] enhancement

#186 Remove Premature Error; Add Loaders
  pages/experiments/[id].tsx
  pages/experiments/[id]/results.tsx
  pages/experiments/index.tsx
Labels: [!priority] high, [component] experimenter interface, [type] enhancement

#192 Use test fixture in ExperimentTabs
  components/ExperimentTabs.test.tsx
Labels: [!priority] medium, [component] experimenter interface, [type] enhancement

#191 Remove Unnecessary Pagination Testing of Experiments Table
  components/ExperimentsTable.test.tsx
Labels: [!priority] medium, [component] experimenter interface, [type] enhancement

#233 Relax the requirement on segment name
  lib/schemas.ts
Labels: [!priority] high, [type] bug
